published_projects = [
    {"name": "Linx", "url": "https://github.com/LinxSolutions", "image": "images/linx.jpg",
        "description": "Learn a new language by watching Netflix.", "tags": "React-Native, Electron, Flask"},
    {"name": "Phishly", "url": "https://github.com/Phishly", "image": "images/phishly.jpg",
        "description": "Train your employees through custom spear phishing attacks.", "tags": "React, Flask, Tensorflow"},
    {"name": "NakedBear", "url": "https://github.com/naked-bear", "image": "images/nakedbear.png",
        "description": "Generate a secure url for any file on your computer to share it with the world.", "tags": "React, Electron, Flask"},
    {"name": "Impulse Hack", "url": "https://itunes.apple.com/us/app/impulsehacker/id1251164412?mt=8", "image": "images/impulsehack.png",
        "description": "Mobile application to register and track impulses.", "tags": "React-Native, D3.js, Sketch"},
    {"name": "OpIn", "url": "https://chrome.google.com/webstore/detail/opin-comment-anywhere/fenapelkfdoiabgffckohbbfggldadek?hl=en-US&gl=US",
        "image": "images/opin.jpg", "description": "Chrome extension used to comment on any website.", "tags": "JavaScript, MongoDB, AWS"},
    {"name": "Passcode", "url": "https://play.google.com/store/apps/details?id=com.aqurytech.savemypasswords",
        "image": "images/passcode.jpg", "description": "Android app that saves all your passwords locally on your device.", "tags": "Java"},
    {"name": "Easy Build", "url": "https://play.google.com/store/apps/details?id=com.aqurytech.easybuild",
        "image": "images/easy_build.jpg", "description": "Install and run your Android app more efficiently.", "tags": "Java, Dropbox API"},
    {"name": "1Step Search", "url": "https://play.google.com/store/apps/details?id=com.onestepsearch.onestepsearch", "image": "images/1step_search.png",
        "description": "Search and download videos, music, photos and more.", "tags": "Java, Python, PHP, MySQL, PayPal API"},
    {"name": "Peer Wifi", "url": "https://devpost.com/software/peer-wifi-x8clai", "image": "images/peer_wifi.png",
        "description": "Buy and sell your mobile hotspot data through tethering.", "tags": "Java, Python, AWS, MongoDB"},
    {"name": "Rutgers Newark: Bus or Rail", "url": "https://play.google.com/store/apps/details?id=com.rutgersrailorbus",
        "image": "images/runbusorrail.png", "description": "Should I take the Rutgers Bus or the Newark Light Rail?", "tags": "React Native, Python"},
    {"name": "Free College PDFs", "url": "http://www.freecollegepdfs.com/", "image": "images/freecollegepdfs.png",
        "description": "Download and upload college textbooks for free.", "tags": "PHP, JavaScript, MySQL"},
    {"name": "HackRUN", "url": "https://hackrun.org", "image": "images/hackrun.png",
        "description": "The first hackathon at Rutgers University Newark.", "tags": "Python, JavaScript, MailChimp"},
    {"name": "Pinetree", "url": "https://play.google.com/store/apps/details?id=com.pinetree", "image": "images/pinetree.png",
        "description": "Message people in your area anonymously for free.", "tags": "React Native, Firebase"},
    {"name": "Emotification", "url": "https://play.google.com/store/apps/details?id=io.hackharvard.emotification", "image": "images/emotification.png",
        "description": "Hear emotionally informed notification tones on Android.", "tags": "Java, Python, AWS, Natural Language Processing"},
    {"name": "Screengif", "url": "https://play.google.com/store/apps/details?id=com.mdislam.screengiff",
        "image": "images/screengif.png", "description": "Record and Share Your Phone Screen as a GIF.", "tags": "Java, FFMPEG"},
    {"name": "Workspaces", "url": "https://chrome.google.com/webstore/detail/workspaces/eehocaoejekpmecmfecdkpohdkgkmoee",
        "image": "images/workspaces.png", "description": "Save all your current tabs and come back to them later.", "tags": "JavaScipt"},
    {"name": "GitReacts", "url": "https://chrome.google.com/webstore/detail/gitreacts/lfjdffifadldpedgddbnaehkecnocdhb", "image": "images/gitreacts.png", "description": "Facebook-like reactions for GitHub repositories.", "tags":
        "Flask, JavaScript, MongoDB"},
    {"name": "Newark LSAMP", "url": "http://newark.gslsamp.rutgers.edu", "image": "images/lsamp.jpg",
        "description": "Website for LSAMP program in Rutgers University Newark.", "tags": "PHP, JavaScript, MySQL"},
    {"name": "jsblocks", "url": "https://chrome.google.com/webstore/detail/jsblocks/icpmhilfekpdgkfliliocpagfleebggh",
        "image": "images/jsblocks.png", "description": "Simple way to block annoying content on any website.", "tags": "JavaScript"},
    {"name": "Salus Mind", "url": "https://github.com/SalusMind", "image": "images/salusmind.png",
        "description": "Mental health monitoring service to save lives", "tags": "React, Flask, IBM Watson"},
    {"name": "Cevo TMS", "url": "https://github.com/cevo-tms", "image": "images/cevotms.png",
        "description": "Simple transportaion management service", "tags": "React Native, Flask, MongoDB, Docker"}
]


hackathon_projects = [
    {"name": "Taylr", "url": "https://devpost.com/software/taylor", "description": "Your personal assistant for interview preparation, tailored just for you.",
        "tags": "python, flask, bluemix, html, css, javascript, sketch, alexa, iot, natural-language-processing, amazon-web-services"},
    {"name": "Peer Wifi", "url": "https://devpost.com/software/peer-wifi-x8clai",
        "description": "Buy and Sell Wifi Hotspots", "tags": "java, php, android-studio, parse, mongodb"},
    {"name": "Rx?", "url": "https://devpost.com/software/rx", "description": "Android app that allows its user to identify the use and dosage of a prescription drug by taking a picture of it.",
        "tags": "python, socket.io, android-studio, microsoft-cognitive-services, flask, drugbankplus, openfda, , natural-language-processing, computer-vision"},
    {"name": "CUNYSlackers (CUNY Discourse)", "url": "https://devpost.com/software/cunyslackers-cuny-discourse",
     "description": "Aggregates and summarizes, using NLP, a classroom's worth of notes into key concepts to inform the college student.", "tags": "html5, css, jquery, bulma, node.js, firebase, bluemix, python, alchemyapi"},
    {"name": "FitBet", "url": "https://devpost.com/software/fitbet-u0zhrq",
        "description": "Stay motivated (and get paid) to hit the gym.", "tags": "java, android-studio, firebase, marvelapp, nessie"},
    {"name": "Layterms", "url": "https://devpost.com/software/layterms", "description": "TL;DR for privacy policies so users can be informed of the data they share",
        "tags": "google-cloud, natural-language-processing, flask, python, javascript, chrome"},
    {"name": "Focus", "url": "https://devpost.com/software/focus-xr5hpf", "description": "Selective noise-cancelling headphones",
        "tags": "pyaudioanalysis, python, raspberry-pi, w3, html5, machine-learning, socket.io, flask, javascript, adobe-creative-suite, photoshop"},
    {"name": "Päwprint", "url": "https://devpost.com/software/pawprint", "description": "A service to help owners find their lost pets using image recognition and public cameras",
        "tags": "javascript, twilio, opencv, python, flask, docker, azure, html5, css3, mysql, blood, sweat, tears, love, more-tears"},
    {"name": "Good₿Miner", "url": "https://devpost.com/software/good-miner",
        "description": "Crowdfunding & fundraising by mining cryptocurrency on the browser", "tags": "python, javascript, mongodb, amazon-web-services"},
    {"name": "Ty", "url": "https://devpost.com/software/ty", "description": "A chat bot to promote healthy conversation between individuals with similar interests.",
        "tags": "azure, clarifai, flask, mongodb, facebook-graph, nltk, python"},
    {"name": "Shane.ai", "url": "https://devpost.com/software/shane-ai", "description": "Personal resume building and designing assistant, done easy!",
        "tags": "python, flask, html5, css, ibm-watson, bluemix, firebase, facebook-graph"},
    {"name": "lawyer.ai", "url": "https://devpost.com/software/lawyer-ai", "description": "Helps Keep Immigration Lawyers on Track and Their Clients Informed",
        "tags": "python, react-native, ibm-watson, natural-language-processing, nltk, nexmo, node.js, scikit-learn"},
    {"name": "RU TRASH", "url": "https://devpost.com/software/ru-trash", "description": "Self moving trashcan that tracks ballistic trajectories to get the trash in the bin - environmentally friendly!",
        "tags": "intel-edison, opencv, arduino, webcam, python, hardware"},
    {"name": "Antarctic Rover", "url": "https://devpost.com/software/antarctic-rover", "description": "Rover to spatially map Antarctica's growing rifts",
        "tags": "socket.io, arduino, webgl, 3js, flask, javascript, python, java, html5, css3, project-tango, ir-sensor"},
    {"name": "HawkEyes", "url": "https://devpost.com/software/hawkeyes-eb5v9z", "description": "Better reading tool for people with Dyslexia",
        "tags": "python, chrome, unity, tobii, opencv, java, javascript, c#, machine-learning, socket.io"},
    {"name": "Echo Native", "url": "https://devpost.com/software/echo-native", "description": "Create Mobile Apps with Amazon Alexa!",
        "tags": "react-native, python, flask, socket.io, alexa, node.js, linode"},
    {"name": "Digital Market Place (DMP)", "url": "https://devpost.com/software/dmp", "description": "A digital market place for e-commerce - revolutionizing online shopping",
     "tags": "flask, python, javascript, react, bulma, html5, css, ziggeo, tokbox"},
    {"name": "Assist Bot", "url": "https://devpost.com/software/assit-bot", "description": "Go Anywhere !",
        "tags": "project-tango, raspberry-pi, intel-edison, intel-xdk, python, raspian, arduino, general-motors-remote, android-studio, node.js"},
    {"name": "CallGov", "url": "https://devpost.com/software/callgov",
        "description": "Call your local representative", "tags": "android, python, java"},
    {"name": "Screengif", "url": "https://devpost.com/software/screengif",
        "description": "Record and share your phone screen as a gif", "tags": "android-studio, java, c"},
    {"name": "Lexiko", "url": "https://devpost.com/software/lexiko", "description": "An app to help patients decipher health data from their medical reports",
        "tags": "flask, beautiful-soup, android, python, bulma, css, html, opencv, , json, javascript, amazon-web-services, socket.io, pil, pytesseract"},
    {"name": "AirPenn - Accessible 3D Drawing, Beautified", "url": "https://devpost.com/software/airpenn",
        "description": "A BLE connected \"Penn\" that allows you to draw in 3D space and beautifies the image for you with AI.", "tags": "javascript, bluetooth, accelerometer, hardware, three.js, json"},
    {"name": "Boing", "url": "https://devpost.com/software/boing-uvilog", "description": "A device that can be configured to associate a specific sound with an action using audio fingerprinting.",
        "tags": "python, raspberry-pi, dejavu, flask, socket.io, twilio, android"},
    {"name": "Image Consultant", "url": "https://devpost.com/software/image-consultant", "description": "Chrome extension that tells you how your next post with affect people's impression of you.",
        "tags": "python, socket.io, flask, r, javascript, ibm-watson, amazon-web-services, facebook-graph"},
    {"name": "Emotification", "url": "https://devpost.com/software/emotification-celogq", "description": "Emotionally informed notification tones",
        "tags": "java, android, python, microsoft-cognitive-services, microsoft, amazon-web-services, natural-language-processing, machine-learning"},
    {"name": "Pinetree", "url": "https://devpost.com/software/pinetree", "description": "Message people in your area anonymously for free.",
        "tags": "javascript, python, java, swift, react-native, firebase, node.js"},
    {"name": "OpIn", "url": "https://devpost.com/software/opin-367m1y", "description": "A Chrome extension that allows you to comment on any webpage.",
        "tags": "javascript, html, css, amazon-web-services, parse, node.js"},
    {"name": "Wall-E, your path guide", "url": "https://devpost.com/software/wall-e-your-path-guide", "description": "New place and scared to navigate? Airports, hospitals, you name it, we will get you anywhere indoors or outdoors.",
        "tags": "java, node.js, python, intel-edison, project-tango, android-studio, 3d-printing, javascript"},
    {"name": "Judge Judy", "url": "https://devpost.com/software/judgejudy", "description": "A slack bot that picks a side in arguments using NLP",
        "tags": "python, amazon-web-services, node.js, bash, google-cloud, bing"},
    {"name": "SafeCam", "url": "https://devpost.com/software/safecam",
        "description": "A desktop security camera that texts you the image of anyone coming near your table", "tags": "shell, python"},
    {"name": "Smile No More", "url": "https://devpost.com/software/smile-no-more",
        "description": "A camera app that does not allow you to smile for photos.", "tags": "python, clarifai, android"},
    {"name": "SMS Programming", "url": "https://devpost.com/software/sms-programming",
        "description": "Text your JavaScript code and get a response.", "tags": "twilio, php"},
    {"name": "Cheers", "url": "https://devpost.com/software/bumpme", "description": "Bump up your fitness",
        "tags": "javascript, html, css, pebble, android, android-studio, node.js, express.js, ajax"},
    {"name": "StudyBuddy", "url": "https://devpost.com/software/studybuddy-65yv1b", "description": "Find study groups around you easily, connect online, share files and chat with friends in a customized interface",
        "tags": "html, html5, javascript, jquery, css, bootstrap, php, mongodb, hipchat, mysql, node.js, domain.com, google-maps"}
]


activities = [
    {"title": "Presented at NY Tech Meetup May 2016", "description": ["\"On Tuesday, May 3rd, three of the Spring 2016 hackNY Student Hackathon‘s winning teams presented at the New York Tech Meetup to a theater packed with local technologists. Accent, the first place winners, and Peer Wifi, the third place winners, were joined by Drone Regulator, winners of our traditional 8-breaker creativity prize.\"",
                                                                      "\"Andy Yu, Md Islam, and Minh Tuan Tran demoed their mobile app, Peer Wifi, which allows users to sell their excess mobile data to others by letting them connect to their mobile hotspots. Users selling their data set prices for usage time and data caps, and users in the vicinity can pay with Paypal or a credit card to connect. The audience laughed and cheered when they demonstrated their live demo had worked by loading a cat video compilation.\""], "image": "images/hackny.jpg", "link": "http://hackny.org/2016/05/spring-2016-hackny-hackathon-winners-demo-at-new-york-tech-meetup/", "link-text": "Read More »"},
    {"title": "StartupBus North America 2017", "description": ["\"This past summer, 20 strangers got on a charter bus headed from New York to New Orleans. For three days they had one goal: Build and launch companies from inside the bus. And then? Compete against each other.\" - Gimlet Media",
                                                               "\"Founded in 2010, StartupBus is building an entrepreneurial ecosystem through unique experiences and inspirational connections. A community run organisation, the underlying vision to all activities is to empower the people that create change in the world and disrupt the status quo.\""], "image": "images/startupbus.jpg", "link": "https://gimletmedia.com/episode/startupbus-part-1-monday/", "link-text": "Listen Podcast »"},
    {"title": "AngelHack's Hackcelerator 2017", "description": ["\"The winning teams from the 55 hackathons we held this Summer all received an invite into our pre-accelerator program, and 37 of them are now in the early-stages of becoming a real startup.\"",
                                                                "\"Over the next twelve weeks they will learn how to take their hackathon prototype to startup reality through our rigorous curriculum, and the wisdom and guidance of expert speakers and mentors.\""], "image": "images/hackcelerator.jpg", "link": "https://angelhack.com/2017/09/27/hackcelerator2017/", "link-text": "Read More »"},
]
